services:
  - type: web
    name: chirper-app
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install
      npm run build
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: chirper-app
          property: url
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STDERR_FORMATTER
        value: Monolog\Formatter\JsonFormatter
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: chirper-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: chirper-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: chirper-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: chirper-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: chirper-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: chirper-db
    databaseName: chirper_db
    user: chirper_user
